### ISSUE TITLE
Инстансы JSON

### ISSUE THREAD

**Issue by roman-bodavskiy** [JekaGrib/ben#13]
В сервере по этому поводу уже было замечание. Вот это можно дерайвить

```

data CopyMsgJSONBody = CopyMsgJSONBody
  { chat_idCM :: UserId,
    from_chat_idCM :: UserId,
    msg_idCM :: MessageId
  }
  deriving (Generic, Show)

instance ToJSON CopyMsgJSONBody where
  toJSON (CopyMsgJSONBody a b c) =
    object ["chat_id" .= a, "from_chat_id" .= b, "message_id" .= c]
  toEncoding (CopyMsgJSONBody a b c) =
    pairs ("chat_id" .= a <> "from_chat_id" .= b <> "message_id" .= c)
```

Если ты хочешь, чтобы поля в json отличались от полей в типах, то можно использовать опции дерайва
https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#v:constructorTagModifier

**Comment by JekaGrib** [comment]
Так получается. Или можно ещё проще?

data CopyMsgJSONBody = CopyMsgJSONBody
  { chatIdCM :: UserId,
    fromChatIdCM :: UserId,
    messageIdCM :: MessageId
  }
  deriving (Generic, Show)

instance ToJSON CopyMsgJSONBody where
  toJSON     = genericToJSON     (optionsSnakeCasePreEraseSuffix "CM")
  toEncoding = genericToEncoding (optionsSnakeCasePreEraseSuffix "CM")

optionsSnakeCasePreEraseSuffix :: String -> Options
optionsSnakeCasePreEraseSuffix suffix = 
  defaultOptions
    { fieldLabelModifier = fromCamelToSnake . eraseSuffix suffix
    }

**Comment by JekaGrib** [comment]
Так получается. Или можно ещё проще?
   ````
data CopyMsgJSONBody = CopyMsgJSONBody
  { chatIdCM :: UserId,
    fromChatIdCM :: UserId,
    messageIdCM :: MessageId
  }
  deriving (Generic, Show)

instance ToJSON CopyMsgJSONBody where
  toJSON     = genericToJSON     (optionsSnakeCasePreEraseSuffix "CM")
  toEncoding = genericToEncoding (optionsSnakeCasePreEraseSuffix "CM")

optionsSnakeCasePreEraseSuffix :: String -> Options
optionsSnakeCasePreEraseSuffix suffix = 
  defaultOptions
    { fieldLabelModifier = fromCamelToSnake . eraseSuffix suffix
    }
````

**Comment by roman-bodavskiy** [comment]
Проще наверно не получится, разве что `toEncoding` можно не определять. Он и так определен через `toJSON` по умолчанию:
```
    toEncoding :: a -> Encoding
    toEncoding = E.value . toJSON
```

**Comment by JekaGrib** [comment]
Previous versions of this library only had the [toJSON](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#v:toJSON) method. Adding [toEncoding](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#v:toEncoding) had two reasons:

1.toEncoding is more efficient for the common case that the output of [toJSON](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#v:toJSON) is directly serialized to a ByteString. Further, expressing either method in terms of the other would be non-optimal.
2.The choice of defaults allows a smooth transition for existing users: Existing instances that do not define [toEncoding](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#v:toEncoding) still compile and have the correct semantics. This is ensured by making the default implementation of [toEncoding](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#v:toEncoding) use [toJSON](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#v:toJSON). This produces correct results, but since it performs an intermediate conversion to a [Value](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#t:Value), it will be less efficient than directly emitting an [Encoding](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#t:Encoding). (this also means that specifying nothing more than instance ToJSON Coord would be sufficient as a generically decoding instance, but there probably exists no good reason to not specify [toEncoding](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#v:toEncoding) in new instances.)

**Comment by JekaGrib** [comment]
#13 https://github.com/JekaGrib/ben/pull/9/commits/75c082421c7c65f7d9a801cee25f2dfd2e10a41e
